-- Local super-admin quick start for manual/e2e flows:
--   docker compose --profile dev up -d && pnpm migrate
--   pnpm seed:admin admin@local admin123 "Local Admin"
-- Then sign in at /admin/login with admin@local / admin123, register a tenant,
-- and verify the welcome email in MailHog at http://localhost:8025.
-- The seed helper hashes the password at runtime; no placeholder hash is committed.
