#!/usr/bin/env bash
set -euo pipefail

: "${POSTGRES_DB:?POSTGRES_DB is required}"
: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${POSTGRES_APP_USER:?POSTGRES_APP_USER is required}"
: "${POSTGRES_APP_PASSWORD:?POSTGRES_APP_PASSWORD is required}"
: "${POSTGRES_ADMIN_USER:?POSTGRES_ADMIN_USER is required}"
: "${POSTGRES_ADMIN_PASSWORD:?POSTGRES_ADMIN_PASSWORD is required}"

psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --set ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_APP_USER}') THEN
    CREATE ROLE ${POSTGRES_APP_USER} LOGIN PASSWORD '${POSTGRES_APP_PASSWORD}' NOBYPASSRLS;
  END IF;

  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_ADMIN_USER}') THEN
    CREATE ROLE ${POSTGRES_ADMIN_USER} LOGIN PASSWORD '${POSTGRES_ADMIN_PASSWORD}' BYPASSRLS;
  END IF;
END
\$\$;

ALTER ROLE ${POSTGRES_APP_USER} WITH LOGIN PASSWORD '${POSTGRES_APP_PASSWORD}' NOBYPASSRLS;
ALTER ROLE ${POSTGRES_ADMIN_USER} WITH LOGIN PASSWORD '${POSTGRES_ADMIN_PASSWORD}' BYPASSRLS;
ALTER DATABASE ${POSTGRES_DB} OWNER TO ${POSTGRES_ADMIN_USER};
ALTER SCHEMA public OWNER TO ${POSTGRES_ADMIN_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_APP_USER};
GRANT USAGE ON SCHEMA public TO ${POSTGRES_APP_USER};
GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_ADMIN_USER};
GRANT ALL PRIVILEGES ON SCHEMA public TO ${POSTGRES_ADMIN_USER};
SQL
